<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Firefly.Desktop/Firefly.Desktop.csproj" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.1" />
  </ItemGroup>
</Project>
